#pragma once
#pragma comment(lib, "consoul_010205_32.lib")

// custom window message ids sent to notify
#define WM_USER_ROWCOLCHANGE    WM_USER + 500
#define WM_USER_ZONEENTER       WM_USER + 501
#define WM_USER_ZONELEAVE       WM_USER + 502
#define WM_USER_ODZONEDRAW      WM_USER + 503
#define WM_USER_MOUSEMSG        WM_USER + 504
#define WM_USER_SETVIRTUALLINE  WM_USER + 505

#define LW_CREATE_FILLEDVEMPTY	1
#define LW_AUTOADJUST_ON_MAXCHARWIDTH	2
#define LW_NO_AUTOREDRAW	4
#define LW_RENDERMODEBYLINE	8
#define LW_TRACK_ZONES	32
#define LW_SENDMESSAGE_NOCALLBACKS	64
#define LW_MULTIZONECLICK	128
#define LW_SEND_MOUSEMOVE	16
#define LW_BKCOLSPILL	256

#define WMPAINTCBK_BEFORE 1
#define WMPAINTCBK_AFTER 2

struct TMsgMouseEvent {
  HWND  hWnd;
  ULONG wParam;
  ULONG wZoneID;
  ULONG wLine;
  ULONG wCol;
  POINT position;
  HCURSOR hCursor;
};
#define TCSMOUSEEVENT struct TMsgMouseEvent
#define PTCSMOUSEEVENT struct TMsgMouseEvent*

struct TMsgODZoneDraw {
  HWND  hWnd;
  ULONG hDC;
  ULONG wZoneID;
  ULONG wLine;
  RECT  rcUpdate;
};
#define TCSODZONEDRAW struct TMsgODZoneDraw
#define PTCSODZONEDRAW struct TMsgODZoneDraw*

// Consoul DLL imports
#define STDCALL __stdcall
#define DLLIMPORT __declspec(dllimport)

DLLIMPORT UINT  STDCALL CSClear(HWND hWnd);
DLLIMPORT HWND STDCALL CSCreateLogWindow(
  HWND hWndParent,
  LONG x, LONG y, LONG width, LONG height,
  LONG lBackColor, LONG lForeColor,
  const PWCHAR sFontName, INT iFontSize, 
  LONG iQueueSize, UINT wCreateAttribs);
DLLIMPORT UINT  STDCALL CSDestroyLogWindow(HWND hWnd);
DLLIMPORT UINT  STDCALL CSGetAutoRedraw(HWND hWnd);
DLLIMPORT UINT  STDCALL CSGetCaretBlinkMs(HWND hWnd);
DLLIMPORT UINT  STDCALL CSGetCaretHeight(HWND hWnd);
DLLIMPORT UINT  STDCALL CSGetCaretPos(HWND hWnd, PUINT lpwLine, PUINT lpwCol);
DLLIMPORT UINT  STDCALL CSGetCaretWidth(HWND hWnd);
DLLIMPORT UINT  STDCALL CSGetCharHeight(HWND hWnd);
DLLIMPORT UINT  STDCALL CSGetCharWidth(HWND hWnd);
DLLIMPORT UINT  STDCALL CSGetFontUnicodeRange(HWND hWnd, ULONG lIndex, PULONG lpdwRetLow, PULONG lpdwRetCount);
DLLIMPORT UINT  STDCALL CSGetHoverCursor(HWND hWnd);
DLLIMPORT UINT  STDCALL CSGetLineHeight(HWND hWnd);
DLLIMPORT UINT  STDCALL CSGetLinePadding(HWND hWnd, UINT wTopOrBottom);
DLLIMPORT UINT  STDCALL CSGetLineSpacing(HWND hWnd, UINT wTopOrBottom);
DLLIMPORT UINT  STDCALL CSGetLineText(HWND hWnd, UINT wLine, UINT wBufferCharLen, PWCHAR lpBuffer, UINT wAsVt100);
DLLIMPORT UINT  STDCALL CSGetMaxCharWidth(HWND hWnd);
DLLIMPORT UINT  STDCALL CSGetMaxVisibleCols(HWND hWnd);
DLLIMPORT UINT  STDCALL CSGetMaxVisibleRows(HWND hWnd);
DLLIMPORT UINT  STDCALL CSGetMouseCursor(HWND hWnd);
DLLIMPORT UINT  STDCALL CSGetMultiZoneClick(HWND hWnd);
DLLIMPORT UINT  STDCALL CSGetQueueCapacity(HWND hWnd);
DLLIMPORT UINT  STDCALL CSGetRenderMode(HWND hWnd);
DLLIMPORT UINT  STDCALL CSGetTopLine(HWND hWnd);
DLLIMPORT UINT  STDCALL CSGetTrackZones(HWND hWnd);
DLLIMPORT UINT  STDCALL CSGetUseCallbacks(HWND hWnd);
DLLIMPORT UINT  STDCALL CSGetVersion(PWCHAR lpstrBuffer);
DLLIMPORT UINT  STDCALL CSGetZoneTag(HWND hWnd, UINT wLine, UINT wZoneID, UINT wBufferSizeBytes, PWCHAR lpBuffer);
DLLIMPORT UINT  STDCALL CSGetZoneText(HWND hWnd, UINT wLine, UINT wZoneID, UINT wBufferSizeBytes, PWCHAR lpBuffer, UINT wDecode);
DLLIMPORT UINT  STDCALL CSIsCaretVisible(HWND hWnd);
DLLIMPORT UINT  STDCALL CSLineCount(HWND hWnd);
DLLIMPORT ULONG STDCALL CSLoadFontUnicodeRanges(HWND hWnd);
DLLIMPORT UINT  STDCALL CSPaintOnDC(HWND hWnd, LONG hDC, LONG lWidth, LONG lHeight, UINT wStartLine, UINT wEndLine);
DLLIMPORT UINT  STDCALL CSPopLines(HWND hWnd, UINT wPopCount);
DLLIMPORT UINT  STDCALL CSPushLine(HWND hWnd, const PWCHAR lpszString, UINT wNoParsing);
DLLIMPORT UINT  STDCALL CSRedrawLine(HWND hWnd, UINT wLine);
DLLIMPORT UINT  STDCALL CSRefreshWindow(HWND hWnd);
DLLIMPORT UINT  STDCALL CSReplaceZone(HWND hWnd, UINT wLine, UINT wZoneID, const PWCHAR lpszReplaceBy, UINT wNoParsing);
DLLIMPORT UINT  STDCALL CSResetAllLines(HWND hWnd);
DLLIMPORT UINT  STDCALL CSSetAlphaTransparency(HWND hWnd, BYTE bPercent);
DLLIMPORT UINT  STDCALL CSSetAutoRedraw(HWND hWnd, UINT wAutoRedraw);
DLLIMPORT UINT  STDCALL CSSetCaretBlinkMs(HWND hWnd, UINT wMillisecs);
DLLIMPORT UINT  STDCALL CSSetCaretHeight(HWND hWnd, UINT wHeight);
DLLIMPORT UINT  STDCALL CSSetCaretPos(HWND hWnd, UINT wLine, UINT wCol);
DLLIMPORT UINT  STDCALL CSSetCaretWidth(HWND hWnd, UINT wWidth);
DLLIMPORT UINT  STDCALL CSSetColorTransparency(HWND hWnd, BYTE bPercent, ULONG dwColor, BYTE bEnabled);
DLLIMPORT UINT  STDCALL CSSetHoverCursor(HWND hWnd, HCURSOR hCursor);
DLLIMPORT UINT  STDCALL CSSetLine(HWND hWnd, UINT wLine, const PWCHAR lpszString, UINT wNoParsing, UINT wNoUpdate);
DLLIMPORT UINT  STDCALL CSSetLinePadding(HWND hWnd, UINT wPadding, UINT wTopOrBottom);
DLLIMPORT UINT  STDCALL CSSetLineSpacing(HWND hWnd, UINT wSpacing, UINT wTopOrBottom);
DLLIMPORT UINT  STDCALL CSSetMouseCursor(HWND hWnd, HCURSOR hCursor);
DLLIMPORT UINT  STDCALL CSSetMultiZoneClick(HWND hWnd, UINT wMulti);
DLLIMPORT UINT  STDCALL CSSetRenderMode(HWND hWnd, UINT wRenderMode);
DLLIMPORT UINT  STDCALL CSSetTrackZones(HWND hWnd, UINT wTrack);
DLLIMPORT UINT  STDCALL CSSetUseCallbacks(HWND hWnd, UINT wUseCallbacks);
DLLIMPORT UINT  STDCALL CSShowCaret(HWND hWnd, UINT wShow);
DLLIMPORT UINT  STDCALL CSTextWidth(HWND hWnd, const PWCHAR lpszText);
DLLIMPORT UINT  STDCALL CSUnloadFontUnicodeRanges(HWND hWnd);
DLLIMPORT UINT  STDCALL CSClickAtCaretPos(HWND hWnd, ULONG dwClickMsg);
DLLIMPORT UINT  STDCALL CSSetOnMouseButtonCallback(HWND hWnd, LPVOID lpEvtProc);
DLLIMPORT UINT  STDCALL CSSetOnVirtuaLineCallback(HWND hWnd, LPVOID lpEvtProc);
DLLIMPORT UINT  STDCALL CSSetOnDrawZoneCallback(HWND hWnd, LPVOID lpEvtProc);
DLLIMPORT UINT  STDCALL CSSetOnWmPaintCallback(HWND hWnd, UINT dwCbkMode, LPVOID lpEvtProc);
